language: node_js
node_js:
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-uxgen' ]; then cd .. && eval "mv $currentfolder generator-uxgen" && cd generator-uxgen; fi

